/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peclparadigmas.Parte1;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Estanteria mostradorPedidos = new Estanteria("mostradorPedido", 10);
    Estanteria mesaPlatos = new Estanteria("mesaPlatos", 20);
    private final int nClientes = 200;
    private final Cocinero c1 = new Cocinero("Cocinero1", mesaPlatos);
    private final Cocinero c2 = new Cocinero("Cocinero2", mesaPlatos);
    private final Cocinero c3 = new Cocinero("Cocinero3", mesaPlatos);
    private final Empleado e1 = new Empleado("Empleado1", mostradorPedidos, mesaPlatos);
    private final Empleado e2 = new Empleado("Empleado2", mostradorPedidos, mesaPlatos);
    private final ActualizarInterfaz ai = new ActualizarInterfaz(this);
    boolean estadoPT = true;

    public Interfaz() throws IOException {
        initComponents();
        ai.start();
        this.c1.start();
        this.c2.start();
        this.c3.start();
        this.e1.start();
        this.e2.start();
        for (int i = 1; i <= nClientes; i++) {
            Cliente cl;
            cl = new Cliente("Cliente" + i, mostradorPedidos);
            cl.start();

        }
    }

    public void actualizar() throws InterruptedException {
        String msgMostradorPedidos = "";
        String msgMesaPlatos = "";

        while (true) {
            Thread.sleep(5);
            try {
                for (int i = 0; i < mostradorPedidos.getListaPedidos().size() - 1; i++) {

                    msgMostradorPedidos += mostradorPedidos.getListaPedidos().get(i) + ", ";

                }
                jTextFieldContenidoMostradorPedido.setText(msgMostradorPedidos);
                msgMostradorPedidos = "";

                for (int j = 0; j < mesaPlatos.getListaPedidos().size() - 1; j++) {

                    msgMesaPlatos += mesaPlatos.getListaPedidos().get(j) + ", ";

                }

                jTextFieldContenidoMesaPlatos.setText(msgMesaPlatos);
                msgMesaPlatos = "";

                jTextFieldCocinero1.setText(c1.getPedido());
                jTextFieldCocinero2.setText(c2.getPedido());
                jTextFieldCocinero3.setText(c3.getPedido());
                jTextFieldEmpleado1.setText(e1.getPedido());
                jTextFieldEmpleado2.setText(e2.getPedido());
            } catch (Exception e) {
                System.out.println(e);

            }

        }
    }
    public String getMostradorPedidos(){
        return jTextFieldContenidoMostradorPedido.getText();
    }
    
    public String getMesaPlatos(){
        return jTextFieldContenidoMesaPlatos.getText();
    }
    public Interfaz getInterfaz(Interfaz interfaz){
        return this;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldContenidoMostradorPedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEmpleado1 = new javax.swing.JTextField();
        jTextFieldEmpleado2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldContenidoMesaPlatos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCocinero1 = new javax.swing.JTextField();
        jTextFieldCocinero2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCocinero3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jToggleButtonPausarTodo = new javax.swing.JToggleButton();
        jToggleButtonPausarEmpleado1 = new javax.swing.JToggleButton();
        jToggleButtonPausarEmpleado2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Contenido del mostrador de pedidos");

        jTextFieldContenidoMostradorPedido.setEditable(false);
        jTextFieldContenidoMostradorPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContenidoMostradorPedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Empleado 1:");

        jLabel3.setText("Empleado 2:");

        jTextFieldEmpleado1.setEditable(false);

        jTextFieldEmpleado2.setEditable(false);

        jLabel4.setText("Contenido de la mesa de platos");

        jTextFieldContenidoMesaPlatos.setEditable(false);
        jTextFieldContenidoMesaPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContenidoMesaPlatosActionPerformed(evt);
            }
        });

        jLabel5.setText("Cocinero 1:");

        jTextFieldCocinero1.setEditable(false);

        jTextFieldCocinero2.setEditable(false);

        jLabel6.setText("Cocinero 2:");

        jTextFieldCocinero3.setEditable(false);
        jTextFieldCocinero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCocinero3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Cocinero 3:");

        jToggleButtonPausarTodo.setText("Pausar todo");
        jToggleButtonPausarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPausarTodoActionPerformed(evt);
            }
        });

        jToggleButtonPausarEmpleado1.setText("Pausar Empleado 1");
        jToggleButtonPausarEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPausarEmpleado1ActionPerformed(evt);
            }
        });

        jToggleButtonPausarEmpleado2.setText("Pausar Empleado 2");
        jToggleButtonPausarEmpleado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPausarEmpleado2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldContenidoMesaPlatos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEmpleado2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jTextFieldCocinero1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 63, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jToggleButtonPausarTodo)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCocinero2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jTextFieldCocinero3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jToggleButtonPausarEmpleado1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jToggleButtonPausarEmpleado2)))))
                        .addGap(0, 155, Short.MAX_VALUE))
                    .addComponent(jTextFieldContenidoMostradorPedido))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldContenidoMostradorPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmpleado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldContenidoMesaPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCocinero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCocinero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCocinero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonPausarTodo)
                    .addComponent(jToggleButtonPausarEmpleado1)
                    .addComponent(jToggleButtonPausarEmpleado2))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldContenidoMostradorPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContenidoMostradorPedidoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldContenidoMostradorPedidoActionPerformed

    private void jTextFieldContenidoMesaPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContenidoMesaPlatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContenidoMesaPlatosActionPerformed

    private void jTextFieldCocinero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCocinero3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCocinero3ActionPerformed

    private void jToggleButtonPausarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPausarTodoActionPerformed

        if (estadoPT) {
            mostradorPedidos.cerrar();
            mesaPlatos.cerrar();
            estadoPT = !estadoPT;
        } else {
            mostradorPedidos.abrir();
            mesaPlatos.abrir();
            estadoPT = !estadoPT;
        }


    }//GEN-LAST:event_jToggleButtonPausarTodoActionPerformed

    private void jToggleButtonPausarEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPausarEmpleado1ActionPerformed
        e1.cambiarEstado();
    }//GEN-LAST:event_jToggleButtonPausarEmpleado1ActionPerformed

    private void jToggleButtonPausarEmpleado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPausarEmpleado2ActionPerformed
        e2.cambiarEstado();
    }//GEN-LAST:event_jToggleButtonPausarEmpleado2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldCocinero1;
    private javax.swing.JTextField jTextFieldCocinero2;
    private javax.swing.JTextField jTextFieldCocinero3;
    private javax.swing.JTextField jTextFieldContenidoMesaPlatos;
    private javax.swing.JTextField jTextFieldContenidoMostradorPedido;
    private javax.swing.JTextField jTextFieldEmpleado1;
    private javax.swing.JTextField jTextFieldEmpleado2;
    private javax.swing.JToggleButton jToggleButtonPausarEmpleado1;
    private javax.swing.JToggleButton jToggleButtonPausarEmpleado2;
    private javax.swing.JToggleButton jToggleButtonPausarTodo;
    // End of variables declaration//GEN-END:variables
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Interfaz().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
}
